### ISSUE TITLE
Can't find the ‘feat_ab_all.tsv’ file 

### ISSUE THREAD

**Issue by ouyangcong3** [zellerlab/crc_meta#3]
I tried the scripts you gave in the https://github.com/zellerlab/crc_meta . when I run ‘Rscript marker_analysis.R species’, it cound not find the ‘feat_ab_all.tsv’ file. In step one ‘Rscript prepare_data.R’ ,it did not produce the ‘feat_ab_all.tsv’ file.

Can you provide me the ‘feat_ab_all.tsv’ file ? or can you give me the correct script ? Many thanks

**Comment by jakob-wirbel** [comment]
So sorry, I hadn't seen this issue!!! Somehow the notification got lost, I'm afraid.
The original problem was (I guess), that the access protocol to the EMBL webservers has been changed and you could therefore not download the files needed to reproduce the analysis. In the latest commit, I just changed the data location to the Zenodo repository which also holds the data. 
Hope that this still helps!
