### ISSUE TITLE
Broken zenodo link

### ISSUE THREAD

**Issue by adw96** [zellerlab/crc_meta#4]
Hi @jakob-wirbel -- thanks for the very interesting paper and for making your code available! 

I'm working through `src/prepare_data.R` and it appears that the Zenodo links are broken, and thus, the data doesn't appear to be available anymore. 

Specifically, line 32, which should execute

`read_tsv("https://zenodo.org/api/files/fe65c9e1-6449-48a3-b001-6c394902a512/meta_all.tsv")`

gives me a 

`Error in open.connection(7L, "rb") : HTTP error 403.`

and similarly for line 41

```
read.table("https://zenodo.org/api/files/fe65c9e1-6449-48a3-b001-6c394902a512/species_profiles_g2_l75_motus2.0.0.tsv", sep='\t', stringsAsFactors = FALSE,
                          header = TRUE, check.names = FALSE, row.names = 1,
                          quote='')
```

```
Error in file(file, "rt") : 
  cannot open the connection to 'https://zenodo.org/api/files/fe65c9e1-6449-48a3-b001-6c394902a512/species_profiles_g2_l75_motus2.0.0.tsv'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://zenodo.org/api/files/fe65c9e1-6449-48a3-b001-6c394902a512/species_profiles_g2_l75_motus2.0.0.tsv': HTTP status was '403 Forbidden'
```

Thanks so much for your help, and for making your data available! 

Amy

**Comment by jakob-wirbel** [comment]
Hi @adw96 
Thank you for spotting this! Zenodo has been updated a couple of days ago, and maybe the API changed? I'm travelling right now, but will check back with this early next week...
Alternatively, you can go to the Zenodo record directly and download the data manually:
https://zenodo.org/records/3517209

Sorry for the delay!

**Comment by adw96** [comment]
Thank you so much for the alternate link, @jakob-wirbel ! That's very helpful. Enjoy your travels and best wishes.

**Comment by jakob-wirbel** [comment]
Okay, it seems that Zenodo is working again. Maybe the API was down for a while after their update :)
So, everything should work again, but I hope that you already managed to download the data!
